version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=Rediet
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=digital_contract_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI (Dashboard)

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Protocol port for Go code
      - "15672:15672" # Dashboard for you
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 10

  auth-service:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth
    environment:
      - DATABASE_DSN=postgres://Rediet:postgres@db:5432/digital_contract_db?sslmode=disable
      - JWT_SECRET=super-secret-production-key-change-me
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    ports:
      - "8080:8080"

  contract-service:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: contract
    environment: 
      - DATABASE_DSN=postgres://Rediet:postgres@db:5432/digital_contract_db?sslmode=disable
      - JWT_SECRET=super-secret-production-key-change-me
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    ports:
      - "8081:8080"

  profile-service:
    build:
      context: ../backend
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: profile
    environment: 
      - DATABASE_DSN=postgres://Rediet:postgres@db:5432/digital_contract_db?sslmode=disable
      - JWT_SECRET=super-secret-production-key-change-me
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy 
    ports:
      - "8082:8082" 

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: global-swagger
    ports:
      - "8085:8080" # Access all docs at http://localhost:8085
    environment:
      # This is the magic part: it tells the UI where to find each service's JSON file
      URLS: "[ 
        { url: 'http://localhost:8080/swagger/doc.json', name: 'Auth Service' }, 
        { url: 'http://localhost:8081/swagger/doc.json', name: 'Contract Service' }, 
        { url: 'http://localhost:8082/swagger/doc.json', name: 'Profile Service' } 
      ]"
    depends_on:
      - auth-service
      - contract-service
      - profile-service
      
volumes:
  postgres_data: